### ISSUE TITLE
Unexpected type variables in generic classes

### ISSUE THREAD

**Issue by jameswald** [square/moshi#1175]
With Kotlin codegen I'm getting a few compiler errors with specific generic class structures. The cases I tried seem to fail with and without `sealed` so that may not be related.

A)

```
sealed class Foo<T>(val a: T) {
    @JsonClass(generateAdapter = true)
    class Bar(a: String) : Foo<String>(a)
}
```

```
Caused by: java.lang.IllegalStateException: Unexpected type variable T
	at com.squareup.moshi.kotlin.codegen.api.AdapterGenerator$generateType$typeRenderer$1.renderTypeVariable(AdapterGenerator.kt:169)
	at com.squareup.moshi.kotlin.codegen.api.TypeRenderer.render(TypeRenderer.kt:103)
	at com.squareup.moshi.kotlin.codegen.api.TypeRenderer.render$default(TypeRenderer.kt:43)
	at com.squareup.moshi.kotlin.codegen.api.DelegateKey.generateProperty(DelegateKey.kt:57)
	at com.squareup.moshi.kotlin.codegen.api.AdapterGenerator.generateType(AdapterGenerator.kt:176)
	at com.squareup.moshi.kotlin.codegen.api.AdapterGenerator.generateFile(AdapterGenerator.kt:145)
	at com.squareup.moshi.kotlin.codegen.JsonClassCodegenProcessor.process(JsonClassCodegenProcessor.kt:112)
	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt)
	at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:147)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:972)
	... 37 more
```

B)

```
sealed class Foo<T> {
    @JsonClass(generateAdapter = true)
    class Bar(a: String) : Foo<String>()
}
```

```
Foo.java:14: error: No property for required constructor parameter a
    public static final class Bar extends com.example.Foo<java.lang.String> {
                        ^

public abstract class Foo<T extends java.lang.Object> {
    
    private Foo() {
        super();
    }
    
    public static final class Bar extends com.example.Foo<java.lang.String> {
        
        public Bar(@org.jetbrains.annotations.NotNull()
        java.lang.String a) {
            super();
        }
    }
}
```

These compile without error:

```
sealed class Foo<T>(val a: T) {
    @JsonClass(generateAdapter = true)
    class Bar : Foo<String>("a")
}
```

```
sealed class Foo<T>(val a: T) {
    @JsonClass(generateAdapter = true)
    class Bar(val b: String) : Foo<String>("a")
}
```

It appears any constructor parameter on the subclass fails when it isn't also a `val` / `var` property but there are a few ways the error can manifest depending on the parent's structure.

**Comment by jameswald** [comment]
This may only be partially related to generics. A) compiles successfully when the generics are removed:

```
sealed class Foo(val a: String) {
    @JsonClass(generateAdapter = true)
    class Bar(a: String) : Foo(a)
}
```

B) still fails without generics:

```
sealed class Foo {
    @JsonClass(generateAdapter = true)
    class Bar(a: String) : Foo()
}
```

**Comment by ZacSweers** [comment]
I believe this is fixed in 1.9.3. Which version are you using?

**Comment by jameswald** [comment]
Confirmed I'm using 1.9.3 and that this compile error is still happening.

**Comment by jameswald-test** [comment]
This is fixed in 1.10.0. 🎊 

I would close the issue but don't have permission.

**Comment by jameswald** [comment]
This is fixed in 1.10.0. 🎊
